[package]
name = "puff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corosensei = {version = "0.1.3", features=["asm-unwind"]}
futures = "0.3.23"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
rand = "0.8.1"
num_cpus = "1.13.1"
lazy_static = "1.4.0"
tower-service = "0.3.2"
axum = {version="0.6.0-rc.2", features=["headers", "ws"]}
futures-util = "0.3.24"
compact_str = {version = "0.6.1", features=["serde"]}
hyper = "0.14.9"
clap = {version = "3.2.20", features = ["env"]}
anyhow = "1.0.64"
serde_json = "1.0.85"
owning_ref = "0.4.1"
chrono = {version = "0.4.22", features = ["serde"]}
serde = {version = "1.0.144", features=["derive"]}
serde_bytes = "0.11.7"
reqwest = "0.11.11"
tracing-subscriber = "0.3.15"
percent-encoding = "2.2.0"
pyo3 = "0.16.6"
bb8-redis = "0.11.0"
uuid = {version = "1.1.2", features=["v4", "fast-rng", "serde"]}
bincode = "1.3.3"

[[example]]
name = "web"
path = "examples/web.rs"

[[example]]
name = "basic"
path = "examples/basic.rs"


#[profile.release]
#opt-level = 3
#strip = true
#debug = false
#codegen-units = 1
#lto = true