[package]
name = "puff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corosensei = {version = "0.1.3", features=["asm-unwind"]}
futures = "0.3.23"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
rand = "0.8.1"
num_cpus = "1.13.1"
lazy_static = "1.4.0"
tower-service = "0.3.2"
axum = "0.6.0-rc.1"
futures-util = "0.3.24"
compact_str = "0.6.1"
hyper = "0.14.9"
derive_more = {version = "0.99.17", features = ["from", "from_str", "as_mut", "as_ref", "add", "add_assign", "default", "deref", "deref_mut"]}
clap = "3.2.20"
anyhow = "1.0.64"

[[example]]
name = "web"
path = "examples/web.rs"
